//
//  NewsListController.m
//  JSReact
//
//  Created by roronoa on 16/4/5.
//  Copyright © 2016年 roronoa. All rights reserved.
//

#import "NewsListController.h"
#import "NewsDetailController.h"
#import "RCTRootView.h"

@interface NewsListController ()

@property (strong, nonatomic) RCTRootView *rootView;
@property(nonatomic, weak) RCTBridge *rootViewBridge;

@end

@implementation NewsListController
RCT_EXPORT_MODULE()

- (dispatch_queue_t)methodQueue
{
   return dispatch_get_main_queue();
}

RCT_EXPORT_METHOD(showNewsDetail:(NSString *)newsid){
    NSLog(@"%@ foo called",  self);
    
    dispatch_async(dispatch_get_main_queue(), ^{
        NewsDetailController *temp = [[NewsDetailController alloc]  init];
        temp.newsid = newsid;
        [self.navigationController pushViewController:temp animated:YES];
    });
}

- (void)viewDidLoad {
    [super viewDidLoad];
    
    self.navigationItem.title = @"list";
    
    __weak typeof(self)  weakSelf = self;
    RCTBridgeModuleProviderBlock block = ^{
        return @[weakSelf];
    };
    
//    NSURL *jsCodeLocation = [NSURL URLWithString:@"http://192.168.1.100:8081/ReactComponent/NewsList.bundle?platform=ios"];
//    NSURL *jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/ReactComponent/NewsList.bundle?platform=ios"];
// For production use, this `NSURL` could instead point to a pre-bundled file on disk:
//
    NSURL *jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"NewsList" withExtension:@"jsbundle"];
//
// generated by "Bundle React Native code and images" build step.
//
//   curl http://localhost:8081/index.ios.bundle -o main.jsbundle
    
    RCTBridge *bridge = [[RCTBridge alloc] initWithBundleURL:jsCodeLocation moduleProvider:block launchOptions:nil];
    NSDictionary *props = @{@"titles" : @"newslist12345"};
    self.rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"NewsList" initialProperties:props];
    self.rootView.frame = self.view.bounds;
    [self.view addSubview:self.rootView];
}
@end
