//
//  NewsDetailController.m
//  JSReact
//
//  Created by roronoa on 16/4/5.
//  Copyright © 2016年 roronoa. All rights reserved.
//

#import "NewsDetailController.h"
#import "RCTRootView.h"

@interface NewsDetailController ()

@property (strong, nonatomic) UIActivityIndicatorView *activityIndicatorView;
@property (strong, nonatomic) RCTRootView *rootView;

@end

@implementation NewsDetailController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    self.view.backgroundColor = [UIColor whiteColor];
    
    NSString *contentURL = [NSString stringWithFormat:@"http://newsapi.eastmoney.com/kuaixun/v2/api/content?newsid=%@&newstype=1&source=app&sys=ios&version=6100", self.newsid];
    NSURL *imageUrl = [NSURL URLWithString:contentURL];
    NSURLRequest *request = [NSURLRequest requestWithURL:imageUrl];
    NSURLSession *session = [NSURLSession sharedSession];
    NSURLSessionDataTask *task = [session dataTaskWithRequest:request
                                            completionHandler:
                                  ^(NSData *data, NSURLResponse *response, NSError *error) {
                                      [self.activityIndicatorView stopAnimating];
                                      
                                      if (error) {
                                          return;
                                      }
                                      
                                      NSError *jError = nil;
                                      NSDictionary *dic = [NSJSONSerialization JSONObjectWithData:data options:NSJSONReadingMutableContainers error:&jError];
                                      
                                      dispatch_async(dispatch_get_main_queue(), ^{
                                          [self addConetentView:dic];
                                      });
                                  }];
    
    [task resume];
    
    self.activityIndicatorView = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];
    self.activityIndicatorView.frame = CGRectMake(0, 0, 30, 30);
    self.activityIndicatorView.center = self.view.center;
    self.activityIndicatorView.hidden = NO;
    [self.view addSubview:self.activityIndicatorView];
    [self.activityIndicatorView startAnimating];
    
}

- (void)addConetentView:(NSDictionary *)dic {
    NSDictionary *newsDict = dic[@"news"];
    if (!newsDict) {
        return;
    }
    
//    NSURL *jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/ReactComponent/NewsDetail.bundle?platform=ios"];
    // For production use, this `NSURL` could instead point to a pre-bundled file on disk:
    //
        NSURL *jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"NewsDetail" withExtension:@"jsbundle"];
    //
    // generated by "Bundle React Native code and images" build step.
    //
    //   curl http://localhost:8081/index.ios.bundle -o main.jsbundle
    
    self.rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation moduleName:@"NewsDetail" initialProperties:newsDict launchOptions:nil];
    self.rootView.frame = self.view.bounds;
    [self.view addSubview:self.rootView];
}

@end
